"""Refatorar modelo DISCResult para usar JSON único para resultados e corrigir mapeamento de chaves

Revision ID: d2bf2695aa10
Revises: 8d09feb8aae6
Create Date: 2025-04-01 21:55:13.547165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bf2695aa10'
down_revision = '8d09feb8aae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disc_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_responses_json', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('calculated_result_json', sa.Text(), nullable=False))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_disc_results_primary_type'), ['primary_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disc_results_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_disc_results_user_email'), ['user_email'], unique=False)
        batch_op.drop_column('disc_levels')
        batch_op.drop_column('raw_responses')
        batch_op.drop_column('disc_scores')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disc_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disc_scores', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('raw_responses', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('disc_levels', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_disc_results_user_email'))
        batch_op.drop_index(batch_op.f('ix_disc_results_timestamp'))
        batch_op.drop_index(batch_op.f('ix_disc_results_primary_type'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('calculated_result_json')
        batch_op.drop_column('raw_responses_json')

    # ### end Alembic commands ###
